storage_path: "host=raportichka-postgres port=5432 user=postgres password=postgres dbname=raportichka sslmode=disable"
schedule_key: "https://disk.yandex.ru/d/kpLwies3wQ53AA"
substitutions_key: "https://disk.yandex.ru/d/VnBUrFQZ7b_pEQ"
sync_interval_hours: 1